// AUTO GENERATED - do not modify
export const definitions = {
  '/v1/contacts': {
    type: 'object',
    properties: {
      location_id: {
        type: 'string',
        pattern:
          '^(([0-9a-fA-F]{24})|(([0-9a-fA-F]{8})-(([0-9a-fA-F]{4}-){3})([0-9a-fA-F]{12})))$',
        description: 'Location ID',
        example: '11e95f8ec39de8fbdb0a4f1a',
      },
      account_number: {
        type: 'string',
        maxLength: 32,
        nullable: true,
        description: 'Contact Account Number',
        example: '54545433332',
      },
      contact_api_id: {
        type: 'string',
        pattern: '^[a-zA-Z0-9]*$',
        maxLength: 64,
        nullable: true,
        description: 'Contact API Id',
        example: '137',
      },
      first_name: {
        type: 'string',
        maxLength: 64,
        nullable: true,
        description: 'First Name',
        example: 'John',
      },
      last_name: {
        type: 'string',
        maxLength: 64,
        description: 'Last Name',
        example: 'Smith',
      },
      cell_phone: {
        type: 'string',
        pattern: '^\\d{10}$',
        minLength: 10,
        maxLength: 10,
        nullable: true,
        description: 'Cell phone of contact',
        example: '3339998822',
      },
      balance: {
        type: 'number',
        format: 'double',
        minimum: -99999999.99,
        maximum: 99999999.99,
        nullable: true,
        description: 'Balance',
        example: 245.36,
      },
      address: {
        type: 'object',
        properties: {
          city: {
            type: 'string',
            pattern: "^[\\w#,.\\-'&\\s/]+$",
            maxLength: 36,
            nullable: true,
            description: 'City of contact',
            example: 'Novi',
          },
          state: {
            type: 'string',
            maxLength: 24,
            nullable: true,
            description: 'State of contact',
            example: 'Michigan',
          },
          postal_code: {
            type: 'string',
            pattern: '^[a-zA-Z0-9\\-\\s]+$',
            minLength: 4,
            maxLength: 10,
            nullable: true,
            description: 'Postal code of contact',
            example: '48375',
          },
          country: {
            type: 'string',
            enum: ['US', 'CA'],
            nullable: true,
            description: 'Country of contact',
            example: 'US',
          },
          street: {
            type: 'string',
            pattern: "^[\\w#,.\\-'&\\s/]+$",
            maxLength: 255,
            nullable: true,
            description: 'Street of contact',
            example: '43155 Main Street STE 2310-C',
          },
        },
        description: 'Address of contact',
      },
      company_name: {
        type: 'string',
        maxLength: 64,
        nullable: true,
        description: 'Company Name',
        example: 'Fortis Payment Systems, LLC',
      },
      header_message: {
        type: 'string',
        maxLength: 250,
        nullable: true,
        description: 'Header Message',
        example: 'This is a sample message for you',
      },
      date_of_birth: {
        type: 'string',
        pattern: '^[\\d]{4}-[\\d]{2}-[\\d]{2}$',
        maxLength: 10,
        nullable: true,
        description: 'Contacts DOB, Format: yyyy-MM-dd',
        example: '2021-12-01',
      },
      email_trx_receipt: {
        type: 'boolean',
        description:
          'Whether or not to email all transactions receipts to contact (1 or 0)',
        example: true,
      },
      home_phone: {
        type: 'string',
        pattern: '^\\d{10}$',
        minLength: 10,
        maxLength: 10,
        nullable: true,
        description: 'Contacts home phone',
        example: '3339998822',
      },
      office_phone: {
        type: 'string',
        pattern: '^\\d{10}$',
        minLength: 10,
        maxLength: 10,
        nullable: true,
        description: 'Contacts office phone',
        example: '3339998822',
      },
      office_phone_ext: {
        type: 'string',
        pattern: '^\\d{1,10}$',
        maxLength: 10,
        nullable: true,
        description: 'Contacts office phone extension for office phone',
        example: '5',
      },
      header_message_type: {
        type: 'integer',
        minimum: 0,
        maximum: 4,
        nullable: true,
        description: 'Header Message Type',
        example: 0,
      },
      update_if_exists: {
        type: 'number',
        format: 'float',
        enum: [1],
        nullable: true,
        description: 'Update If Exists',
        example: 1,
      },
      contact_c1: {
        type: 'string',
        maxLength: 128,
        nullable: true,
        description: 'Custom field 1 for api users to store custom data',
        example: 'any',
      },
      contact_c2: {
        type: 'string',
        maxLength: 128,
        nullable: true,
        description: 'Custom field 2 for api users to store custom data',
        example: 'anything',
      },
      contact_c3: {
        type: 'string',
        maxLength: 128,
        nullable: true,
        description: 'Custom field 3 for api users to store custom data',
        example: 'something',
      },
      parent_id: {
        type: 'string',
        pattern:
          '^(([0-9a-fA-F]{24})|(([0-9a-fA-F]{8})-(([0-9a-fA-F]{4}-){3})([0-9a-fA-F]{12})))$',
        nullable: true,
        description: 'Parent Id',
        example: '11e95f8ec39de8fbdb0a4f1a',
      },
      email: {
        type: 'string',
        format: 'email',
        maxLength: 64,
        nullable: true,
        description: 'Email of contact',
        example: 'email@domain.com',
      },
    },
    required: ['location_id', 'last_name'],
  },
} as const

export type OpenApiSpec = typeof definitions
